---
title: "Evolution of solar energy production and use."
author: "Laia Porcar, Luis Marcos López, Philippe Robert"
date: "11/08/2022"
output:
  html_document:
    keep_md: yes
    toc: yes
    df_print: kable
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
```


```{r, results="hide", message = FALSE}
# Installs
# install.packages("caret")
# install.packages("car")
# install.packages("ggplot2")
# install.packages("devtools")


# Libraries
library(knitr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggcorrplot)
library(devtools) 
library(caret)
library(car)
library(kableExtra)
library(ggpubr)
library(readxl)
library(lmtest) 
library(forecast)
library(DIMORA)

```



```{r results = 'asis'}
# Read the dataset
file_path <- getwd()
paste(file_path)

df_capac <- read.csv(paste0(file_path, "/installed-solar-PV-capacity.csv"),header=TRUE)
df_capit <- read.csv(paste0(file_path, "/per-capita-solar.csv"),header=TRUE)
df_prim <- read.csv(paste0(file_path, "/primary-energy-consumption-from-solar.csv"),header=TRUE)
df_shar <- read.csv(paste0(file_path, "/share-electricity-solar.csv"),header=TRUE)
df_consump <- read.csv(paste0(file_path, "/solar-energy-consumption.csv"),header=TRUE)
df_cumcapac <- read.csv(paste0(file_path, "/solar-pv-cumulative-capacity.csv"),header=TRUE)
df_price <- read.csv(paste0(file_path, "/solar-pv-prices.csv"),header=TRUE)
df_totconsumpcapita <- read.csv(paste0(file_path, "/per-capita-energy.csv"), header=TRUE)


df_capac[1:150,] %>%
  kable(format = "html", col.names = colnames(df_capac)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_capit[1:150,] %>%
  kable(format = "html", col.names = colnames(df_capit)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_prim[1:150,] %>%
  kable(format = "html", col.names = colnames(df_prim)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_shar[1:150,] %>%
  kable(format = "html", col.names = colnames(df_shar)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_consump[1:150,] %>%
  kable(format = "html", col.names = colnames(df_consump)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_cumcapac[1:150,] %>%
  kable(format = "html", col.names = colnames(df_cumcapac)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_price[1:150,] %>%
  kable(format = "html", col.names = colnames(df_price)) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")

df_totconsumpcapita[1:150,] %>% 
  kable(format = "html", col.names = colnames(df_totconsumpcapita)) %>% 
  kable_styling() %>% 
  kableExtra::scroll_box(width = "100%", height = "300ppx")

```


```{r results = 'asis'}

entity <- 'Spain'

df_capacity <- df_capac %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_capita <- df_capit %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_primary <- df_prim %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_share <- df_shar %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_consumption <- df_consump %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_cumcap <- df_cumcapac %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_totconsump <- df_totconsumpcapita %>% filter(Entity == entity) %>% select(-c(Entity, Code))
df_price <- select(df_price,-c(Entity, Code))

df <- merge(df_capacity,df_capita, by="Year", all = TRUE) #to fill the non existant values with NA
df <- merge(df,df_primary,by="Year", all = TRUE)
df <- merge(df,df_share,by="Year", all = TRUE)
df <- merge(df,df_consumption,by="Year", all = TRUE)
df <- merge(df,df_cumcap,by="Year", all = TRUE)
df <- merge(df,df_price,by="Year", all = TRUE)
df <- merge(df,df_totconsump,by="Year", all = TRUE)

df[is.na(df)] <- 0 #change NA to 0


```




# Exploratory data analysis


# Apply stuff from the lectures


```{r results = 'asis'}

str(df)


```


```{r results = 'asis'}


cap_consump <- df$Solar.per.capita..kWh...equivalent[25:57]
tt<- 1:NROW(cap_consump)

plot(tt, cap_consump, xlab="Time", ylab="Solar per capita kWh")
acf(cap_consump)

```




```{r results = 'asis'}

##fit a linear regression model 
fit1 <- lm(cap_consump ~ tt)
summary(fit1)

##plot of the model
plot(tt, cap_consump, xlab="Time", ylab="Solar per capita kWh")
abline(fit1, col=3)

##check the residuals? are they autocorrelated? Test of DW
dwtest(fit1)

##check the residuals
resfit1<- residuals(fit1)
plot(resfit1,xlab="Time", ylab="residuals" )


```



```{r results = 'asis'}

##let us do the same with a linear model for time series, so we transform the data into a ts object
cap_consump.ts <- ts(cap_consump, frequency = 4)
ts.plot(cap_consump.ts, type="o")

## we fit a linear model with the tslm function
fitts<- tslm(cap_consump.ts~trend)

###obviously it gives the same results of the first model
summary(fitts)

dwtest(fitts)

```



```{r results = 'asis'}

#plot(cap_consump, type="b")
plot(cap_consump, type= "b",xlab="Year", ylab="Solar per capita kWh",  pch=16, lty=3, xaxt="n", cex=0.6)
plot(cumsum(cap_consump), type="b", xlab="Year", ylab="Solar per capita kWh",  pch=16, lty=3, xaxt="n", cex=0.6)

```



```{r results = 'asis'}

bm_cap<-BM(cap_consump,display = T)
summary(bm_cap)

###prediction (out-of-sample)
pred_bmcap<- predict(bm_cap, newx=c(1:50))
pred.instcap<- make.instantaneous(pred_bmcap)

###plot of fitted model 
plot(cap_consump, type= "b",xlab="Year", ylab="Solar per capita kWh",  pch=16, lty=3, xaxt="n", cex=0.6)
lines(pred.instcap, lwd=2, col=2)

```



```{r results = 'asis'}

###we estimate the model with 75% of the data
bm_cap75<-BM(cap_consump[1:25],display = T)
summary(bm_cap75)

pred_bmcap75<- predict(bm_cap75, newx=c(1:50))
pred.instcap75<- make.instantaneous(pred_bmcap75)

plot(cap_consump, type= "b",xlab="Year", ylab="Solar per capita kWh",  pch=16, lty=3, xaxt="n", cex=0.6)
lines(pred.instcap75, lwd=2, col=2)
```



```{r results = 'asis'}

###Comparison between models (instantaneous)
###instantaneous
plot(cap_consump, type= "b",xlab="Year", ylab="Solar per capita kWh",  pch=16, lty=3, xaxt="n", cex=0.6)
lines(pred.instcap75, lwd=2, col=2)
lines(pred.instcap, lwd=2, col=4)

###Comparison between models (cumulative)
plot(cumsum(cap_consump), type= "b",xlab="Year", ylab="Annual sales",  pch=16, lty=3, xaxt="n", cex=0.6)
lines(pred_bmcap75, lwd=2, col=2)
lines(pred_bmcap, lwd=2, col=4)

```


```{r results = 'asis'}


###GBMr1
GBMr1_cap <- GBM(cap_consump,shock = "rett",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 15,32,-0.1))
GBMr1_cap <- GBM(cap_consump,shock = "rett",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 15,32,-0.2))
GBMr1_cap <- GBM(cap_consump,shock = "rett",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 15,32,-1))
GBMr1_cap <- GBM(cap_consump,shock = "rett",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 15,32,-0.8))
GBMr1_cap <- GBM(cap_consump,shock = "rett",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 15,32,-2))
 

######GBMe1
GBMe1 <- GBM(cap_consump,shock = "exp",nshock = 1,prelimestimates = c(1.243162e+04, 2.424655e-05, 3.283666e-01, 20, -0.1,0.2)) #funcionan varios numeros
summary(GBMe1)

pred_GBMe1<- predict(GBMe1, newx=c(1:50))
pred_GBMe1.inst<- make.instantaneous(pred_GBMe1)

plot(cap_consump, type= "b",xlab="Quarter", ylab="Quarterly revenues",  pch=16, lty=3, cex=0.6, xlim=c(1,60))
lines(pred_GBMe1.inst, lwd=2, col=2) 


```


```{r results = 'asis'}

######GGM 
GGM_cap<- GGM(cap_consump, prelimestimates=c(1.243162e+04, 0.001, 0.01,  2.424655e-05, 3.283666e-01
                                             ))
summary(GGM_cap)

pred_GGM_cap<- predict(GGM_cap, newx=c(1:60))
pred_GGM_cap.inst<- make.instantaneous(pred_GGM_tw)

plot(cap_consump, type= "b",xlab="Quarter", ylab="Quarterly revenues",  pch=16, lty=3, cex=0.6, xlim=c(1,60))
lines(pred_GGM_cap.inst, lwd=2, col=2)

```


```{r results = 'asis'}


```


```{r results = 'asis'}


```


```{r results = 'asis'}


```


```{r results = 'asis'}


```
